name: Update CDN

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make POST Request
        uses: fjogeleit/http-request-action@v1.9.0
        with:
          url: 'https://i-rule.tomat.dev/'
          method: 'POST'
          data: ${{ secrets.DATA }}
